INSERT INTO music.country (id, country_name, iso3) VALUES (1, 'Japan', 'JPN');
INSERT INTO music.country (id, country_name, iso3) VALUES (2, 'Indonesia', 'IDN');
INSERT INTO music.country (id, country_name, iso3) VALUES (3, 'India', 'IND');
INSERT INTO music.country (id, country_name, iso3) VALUES (4, 'Philippines', 'PHL');
INSERT INTO music.country (id, country_name, iso3) VALUES (5, 'China', 'CHN');
INSERT INTO music.country (id, country_name, iso3) VALUES (6, 'Brazil', 'BRA');
INSERT INTO music.country (id, country_name, iso3) VALUES (7, 'Korea, South', 'KOR');
INSERT INTO music.country (id, country_name, iso3) VALUES (8, 'Mexico', 'MEX');
INSERT INTO music.country (id, country_name, iso3) VALUES (9, 'Egypt', 'EGY');
INSERT INTO music.country (id, country_name, iso3) VALUES (10, 'United States', 'USA');
INSERT INTO music.country (id, country_name, iso3) VALUES (11, 'Russia', 'RUS');
INSERT INTO music.country (id, country_name, iso3) VALUES (12, 'Thailand', 'THA');
INSERT INTO music.country (id, country_name, iso3) VALUES (13, 'Argentina', 'ARG');
INSERT INTO music.country (id, country_name, iso3) VALUES (14, 'Bangladesh', 'BGD');
INSERT INTO music.country (id, country_name, iso3) VALUES (15, 'Nigeria', 'NGA');
INSERT INTO music.country (id, country_name, iso3) VALUES (16, 'Turkey', 'TUR');
INSERT INTO music.country (id, country_name, iso3) VALUES (17, 'Pakistan', 'PAK');
INSERT INTO music.country (id, country_name, iso3) VALUES (18, 'Iran', 'IRN');
INSERT INTO music.country (id, country_name, iso3) VALUES (19, 'Congo (Kinshasa)', 'COD');
INSERT INTO music.country (id, country_name, iso3) VALUES (20, 'Vietnam', 'VNM');
INSERT INTO music.country (id, country_name, iso3) VALUES (21, 'France', 'FRA');
INSERT INTO music.country (id, country_name, iso3) VALUES (22, 'United Kingdom', 'GBR');
INSERT INTO music.country (id, country_name, iso3) VALUES (23, 'Peru', 'PER');
INSERT INTO music.country (id, country_name, iso3) VALUES (24, 'Colombia', 'COL');
INSERT INTO music.country (id, country_name, iso3) VALUES (25, 'Angola', 'AGO');
INSERT INTO music.country (id, country_name, iso3) VALUES (26, 'Malaysia', 'MYS');
INSERT INTO music.country (id, country_name, iso3) VALUES (27, 'Hong Kong', 'HKG');
INSERT INTO music.country (id, country_name, iso3) VALUES (28, 'Sudan', 'SDN');
INSERT INTO music.country (id, country_name, iso3) VALUES (29, 'Chile', 'CHL');
INSERT INTO music.country (id, country_name, iso3) VALUES (30, 'Saudi Arabia', 'SAU');
INSERT INTO music.country (id, country_name, iso3) VALUES (31, 'Tanzania', 'TZA');
INSERT INTO music.country (id, country_name, iso3) VALUES (32, 'Iraq', 'IRQ');
INSERT INTO music.country (id, country_name, iso3) VALUES (33, 'Singapore', 'SGP');
INSERT INTO music.country (id, country_name, iso3) VALUES (34, 'Kenya', 'KEN');
INSERT INTO music.country (id, country_name, iso3) VALUES (35, 'Burma', 'MMR');
INSERT INTO music.country (id, country_name, iso3) VALUES (36, 'Canada', 'CAN');
INSERT INTO music.country (id, country_name, iso3) VALUES (37, 'Australia', 'AUS');
INSERT INTO music.country (id, country_name, iso3) VALUES (38, 'Côte D’Ivoire', 'CIV');
INSERT INTO music.country (id, country_name, iso3) VALUES (39, 'Spain', 'ESP');
INSERT INTO music.country (id, country_name, iso3) VALUES (40, 'South Africa', 'ZAF');
INSERT INTO music.country (id, country_name, iso3) VALUES (41, 'Morocco', 'MAR');
INSERT INTO music.country (id, country_name, iso3) VALUES (42, 'Jordan', 'JOR');
INSERT INTO music.country (id, country_name, iso3) VALUES (43, 'Afghanistan', 'AFG');
INSERT INTO music.country (id, country_name, iso3) VALUES (44, 'Germany', 'DEU');
INSERT INTO music.country (id, country_name, iso3) VALUES (45, 'Algeria', 'DZA');
INSERT INTO music.country (id, country_name, iso3) VALUES (46, 'Bolivia', 'BOL');
INSERT INTO music.country (id, country_name, iso3) VALUES (47, 'Ethiopia', 'ETH');
INSERT INTO music.country (id, country_name, iso3) VALUES (48, 'Ukraine', 'UKR');
INSERT INTO music.country (id, country_name, iso3) VALUES (49, 'Yemen', 'YEM');
INSERT INTO music.country (id, country_name, iso3) VALUES (50, 'Italy', 'ITA');
INSERT INTO music.country (id, country_name, iso3) VALUES (51, 'Korea, North', 'PRK');
INSERT INTO music.country (id, country_name, iso3) VALUES (52, 'Taiwan', 'TWN');
INSERT INTO music.country (id, country_name, iso3) VALUES (53, 'Ecuador', 'ECU');
INSERT INTO music.country (id, country_name, iso3) VALUES (54, 'Madagascar', 'MDG');
INSERT INTO music.country (id, country_name, iso3) VALUES (55, 'Dominican Republic', 'DOM');
INSERT INTO music.country (id, country_name, iso3) VALUES (56, 'United Arab Emirates', 'ARE');
INSERT INTO music.country (id, country_name, iso3) VALUES (57, 'Guatemala', 'GTM');
INSERT INTO music.country (id, country_name, iso3) VALUES (58, 'Cameroon', 'CMR');
INSERT INTO music.country (id, country_name, iso3) VALUES (59, 'Uzbekistan', 'UZB');
INSERT INTO music.country (id, country_name, iso3) VALUES (60, 'Ghana', 'GHA');
INSERT INTO music.country (id, country_name, iso3) VALUES (61, 'Azerbaijan', 'AZE');
INSERT INTO music.country (id, country_name, iso3) VALUES (62, 'Cuba', 'CUB');
INSERT INTO music.country (id, country_name, iso3) VALUES (63, 'Cambodia', 'KHM');
INSERT INTO music.country (id, country_name, iso3) VALUES (64, 'Somalia', 'SOM');
INSERT INTO music.country (id, country_name, iso3) VALUES (65, 'Belarus', 'BLR');
INSERT INTO music.country (id, country_name, iso3) VALUES (66, 'Mali', 'MLI');
INSERT INTO music.country (id, country_name, iso3) VALUES (67, 'Venezuela', 'VEN');
INSERT INTO music.country (id, country_name, iso3) VALUES (68, 'Malawi', 'MWI');
INSERT INTO music.country (id, country_name, iso3) VALUES (69, 'Romania', 'ROU');
INSERT INTO music.country (id, country_name, iso3) VALUES (70, 'Paraguay', 'PRY');
INSERT INTO music.country (id, country_name, iso3) VALUES (71, 'Austria', 'AUT');
INSERT INTO music.country (id, country_name, iso3) VALUES (72, 'Syria', 'SYR');
INSERT INTO music.country (id, country_name, iso3) VALUES (73, 'Congo (Brazzaville)', 'COG');
INSERT INTO music.country (id, country_name, iso3) VALUES (74, 'Kazakhstan', 'KAZ');
INSERT INTO music.country (id, country_name, iso3) VALUES (75, 'Poland', 'POL');
INSERT INTO music.country (id, country_name, iso3) VALUES (76, 'Hungary', 'HUN');
INSERT INTO music.country (id, country_name, iso3) VALUES (77, 'Zambia', 'ZMB');
INSERT INTO music.country (id, country_name, iso3) VALUES (78, 'Guinea', 'GIN');
INSERT INTO music.country (id, country_name, iso3) VALUES (79, 'Uganda', 'UGA');
INSERT INTO music.country (id, country_name, iso3) VALUES (80, 'Burkina Faso', 'BFA');
INSERT INTO music.country (id, country_name, iso3) VALUES (81, 'Zimbabwe', 'ZWE');
INSERT INTO music.country (id, country_name, iso3) VALUES (82, 'New Zealand', 'NZL');
INSERT INTO music.country (id, country_name, iso3) VALUES (83, 'Oman', 'OMN');
INSERT INTO music.country (id, country_name, iso3) VALUES (84, 'Netherlands', 'NLD');
INSERT INTO music.country (id, country_name, iso3) VALUES (85, 'Mongolia', 'MNG');
INSERT INTO music.country (id, country_name, iso3) VALUES (86, 'Serbia', 'SRB');
INSERT INTO music.country (id, country_name, iso3) VALUES (87, 'Bulgaria', 'BGR');
INSERT INTO music.country (id, country_name, iso3) VALUES (88, 'Czechia', 'CZE');
INSERT INTO music.country (id, country_name, iso3) VALUES (89, 'Uruguay', 'URY');
INSERT INTO music.country (id, country_name, iso3) VALUES (90, 'Qatar', 'QAT');
INSERT INTO music.country (id, country_name, iso3) VALUES (91, 'Honduras', 'HND');
INSERT INTO music.country (id, country_name, iso3) VALUES (92, 'Tunisia', 'TUN');
INSERT INTO music.country (id, country_name, iso3) VALUES (93, 'Mozambique', 'MOZ');
INSERT INTO music.country (id, country_name, iso3) VALUES (94, 'Ireland', 'IRL');
INSERT INTO music.country (id, country_name, iso3) VALUES (95, 'Senegal', 'SEN');
INSERT INTO music.country (id, country_name, iso3) VALUES (96, 'Libya', 'LBY');
INSERT INTO music.country (id, country_name, iso3) VALUES (97, 'Georgia', 'GEO');
INSERT INTO music.country (id, country_name, iso3) VALUES (98, 'Chad', 'TCD');
INSERT INTO music.country (id, country_name, iso3) VALUES (99, 'Denmark', 'DNK');
INSERT INTO music.country (id, country_name, iso3) VALUES (100, 'Armenia', 'ARM');
INSERT INTO music.country (id, country_name, iso3) VALUES (101, 'Mauritania', 'MRT');
INSERT INTO music.country (id, country_name, iso3) VALUES (102, 'Kyrgyzstan', 'KGZ');
INSERT INTO music.country (id, country_name, iso3) VALUES (103, 'Turkmenistan', 'TKM');
INSERT INTO music.country (id, country_name, iso3) VALUES (104, 'Niger', 'NER');
INSERT INTO music.country (id, country_name, iso3) VALUES (105, 'Nicaragua', 'NIC');
INSERT INTO music.country (id, country_name, iso3) VALUES (106, 'Liberia', 'LBR');
INSERT INTO music.country (id, country_name, iso3) VALUES (107, 'Haiti', 'HTI');
INSERT INTO music.country (id, country_name, iso3) VALUES (108, 'Nepal', 'NPL');
INSERT INTO music.country (id, country_name, iso3) VALUES (109, 'Sweden', 'SWE');
INSERT INTO music.country (id, country_name, iso3) VALUES (110, 'Eritrea', 'ERI');
INSERT INTO music.country (id, country_name, iso3) VALUES (111, 'Sierra Leone', 'SLE');
INSERT INTO music.country (id, country_name, iso3) VALUES (112, 'Israel', 'ISR');
INSERT INTO music.country (id, country_name, iso3) VALUES (113, 'Panama', 'PAN');
INSERT INTO music.country (id, country_name, iso3) VALUES (114, 'Togo', 'TGO');
INSERT INTO music.country (id, country_name, iso3) VALUES (115, 'Gabon', 'GAB');
INSERT INTO music.country (id, country_name, iso3) VALUES (116, 'Croatia', 'HRV');
INSERT INTO music.country (id, country_name, iso3) VALUES (117, 'Tajikistan', 'TJK');
INSERT INTO music.country (id, country_name, iso3) VALUES (118, 'Benin', 'BEN');
INSERT INTO music.country (id, country_name, iso3) VALUES (119, 'Laos', 'LAO');
INSERT INTO music.country (id, country_name, iso3) VALUES (120, 'Sri Lanka', 'LKA');
INSERT INTO music.country (id, country_name, iso3) VALUES (121, 'Rwanda', 'RWA');
INSERT INTO music.country (id, country_name, iso3) VALUES (122, 'Central African Republic', 'CAF');
INSERT INTO music.country (id, country_name, iso3) VALUES (123, 'Latvia', 'LVA');
INSERT INTO music.country (id, country_name, iso3) VALUES (124, 'Norway', 'NOR');
INSERT INTO music.country (id, country_name, iso3) VALUES (125, 'Moldova', 'MDA');
INSERT INTO music.country (id, country_name, iso3) VALUES (126, 'Greece', 'GRC');
INSERT INTO music.country (id, country_name, iso3) VALUES (127, 'Burundi', 'BDI');
INSERT INTO music.country (id, country_name, iso3) VALUES (128, 'Finland', 'FIN');
INSERT INTO music.country (id, country_name, iso3) VALUES (129, 'Macedonia', 'MKD');
INSERT INTO music.country (id, country_name, iso3) VALUES (130, 'Kuwait', 'KWT');
INSERT INTO music.country (id, country_name, iso3) VALUES (131, 'Jamaica', 'JAM');
INSERT INTO music.country (id, country_name, iso3) VALUES (132, 'Lithuania', 'LTU');
INSERT INTO music.country (id, country_name, iso3) VALUES (133, 'El Salvador', 'SLV');
INSERT INTO music.country (id, country_name, iso3) VALUES (134, 'Djibouti', 'DJI');
INSERT INTO music.country (id, country_name, iso3) VALUES (135, 'Portugal', 'PRT');
INSERT INTO music.country (id, country_name, iso3) VALUES (136, 'Estonia', 'EST');
INSERT INTO music.country (id, country_name, iso3) VALUES (137, 'Slovakia', 'SVK');
INSERT INTO music.country (id, country_name, iso3) VALUES (138, 'Albania', 'ALB');
INSERT INTO music.country (id, country_name, iso3) VALUES (139, 'Lebanon', 'LBN');
INSERT INTO music.country (id, country_name, iso3) VALUES (140, 'Guinea-Bissau', 'GNB');
INSERT INTO music.country (id, country_name, iso3) VALUES (141, 'South Sudan', 'SSD');
INSERT INTO music.country (id, country_name, iso3) VALUES (142, 'Papua New Guinea', 'PNG');
INSERT INTO music.country (id, country_name, iso3) VALUES (143, 'Lesotho', 'LSO');
INSERT INTO music.country (id, country_name, iso3) VALUES (144, 'Cyprus', 'CYP');
INSERT INTO music.country (id, country_name, iso3) VALUES (145, 'Namibia', 'NAM');
INSERT INTO music.country (id, country_name, iso3) VALUES (146, 'Costa Rica', 'CRI');
INSERT INTO music.country (id, country_name, iso3) VALUES (147, 'Slovenia', 'SVN');
INSERT INTO music.country (id, country_name, iso3) VALUES (148, 'Bosnia And Herzegovina', 'BIH');
INSERT INTO music.country (id, country_name, iso3) VALUES (149, 'Bahamas, The', 'BHS');
INSERT INTO music.country (id, country_name, iso3) VALUES (150, 'Botswana', 'BWA');
INSERT INTO music.country (id, country_name, iso3) VALUES (151, 'Suriname', 'SUR');
INSERT INTO music.country (id, country_name, iso3) VALUES (152, 'Timor-Leste', 'TLS');
INSERT INTO music.country (id, country_name, iso3) VALUES (153, 'Kosovo', 'XKS');
INSERT INTO music.country (id, country_name, iso3) VALUES (154, 'Guyana', 'GUY');
INSERT INTO music.country (id, country_name, iso3) VALUES (155, 'Equatorial Guinea', 'GNQ');
INSERT INTO music.country (id, country_name, iso3) VALUES (156, 'Belgium', 'BEL');
INSERT INTO music.country (id, country_name, iso3) VALUES (157, 'Maldives', 'MDV');
INSERT INTO music.country (id, country_name, iso3) VALUES (158, 'Montenegro', 'MNE');
INSERT INTO music.country (id, country_name, iso3) VALUES (159, 'Bahrain', 'BHR');
INSERT INTO music.country (id, country_name, iso3) VALUES (160, 'Mauritius', 'MUS');
INSERT INTO music.country (id, country_name, iso3) VALUES (161, 'Switzerland', 'CHE');
INSERT INTO music.country (id, country_name, iso3) VALUES (162, 'Iceland', 'ISL');
INSERT INTO music.country (id, country_name, iso3) VALUES (163, 'Cabo Verde', 'CPV');
INSERT INTO music.country (id, country_name, iso3) VALUES (164, 'Luxembourg', 'LUX');
INSERT INTO music.country (id, country_name, iso3) VALUES (165, 'Barbados', 'BRB');
INSERT INTO music.country (id, country_name, iso3) VALUES (166, 'Comoros', 'COM');
INSERT INTO music.country (id, country_name, iso3) VALUES (167, 'Bhutan', 'BTN');
INSERT INTO music.country (id, country_name, iso3) VALUES (168, 'Swaziland', 'SWZ');
INSERT INTO music.country (id, country_name, iso3) VALUES (169, 'Solomon Islands', 'SLB');
INSERT INTO music.country (id, country_name, iso3) VALUES (170, 'Fiji', 'FJI');
INSERT INTO music.country (id, country_name, iso3) VALUES (171, 'Saint Lucia', 'LCA');
INSERT INTO music.country (id, country_name, iso3) VALUES (172, 'Sao Tome And Principe', 'STP');
INSERT INTO music.country (id, country_name, iso3) VALUES (173, 'Vanuatu', 'VUT');
INSERT INTO music.country (id, country_name, iso3) VALUES (174, 'Brunei', 'BRN');
INSERT INTO music.country (id, country_name, iso3) VALUES (175, 'Monaco', 'MCO');
INSERT INTO music.country (id, country_name, iso3) VALUES (176, 'Trinidad And Tobago', 'TTO');
INSERT INTO music.country (id, country_name, iso3) VALUES (177, 'Samoa', 'WSM');
INSERT INTO music.country (id, country_name, iso3) VALUES (178, 'Liechtenstein', 'LIE');
INSERT INTO music.country (id, country_name, iso3) VALUES (179, 'Gambia, The', 'GMB');
INSERT INTO music.country (id, country_name, iso3) VALUES (180, 'Kiribati', 'KIR');
INSERT INTO music.country (id, country_name, iso3) VALUES (181, 'Seychelles', 'SYC');
INSERT INTO music.country (id, country_name, iso3) VALUES (182, 'Marshall Islands', 'MHL');
INSERT INTO music.country (id, country_name, iso3) VALUES (183, 'Saint Vincent And The Grenadines', 'VCT');
INSERT INTO music.country (id, country_name, iso3) VALUES (184, 'Tonga', 'TON');
INSERT INTO music.country (id, country_name, iso3) VALUES (185, 'Antigua And Barbuda', 'ATG');
INSERT INTO music.country (id, country_name, iso3) VALUES (186, 'Andorra', 'AND');
INSERT INTO music.country (id, country_name, iso3) VALUES (187, 'Belize', 'BLZ');
INSERT INTO music.country (id, country_name, iso3) VALUES (188, 'Dominica', 'DMA');
INSERT INTO music.country (id, country_name, iso3) VALUES (189, 'Saint Kitts And Nevis', 'KNA');
INSERT INTO music.country (id, country_name, iso3) VALUES (190, 'American Samoa', 'ASM');
INSERT INTO music.country (id, country_name, iso3) VALUES (191, 'Malta', 'MLT');
INSERT INTO music.country (id, country_name, iso3) VALUES (192, 'Micronesia, Federated States Of', 'FSM');
INSERT INTO music.country (id, country_name, iso3) VALUES (193, 'Tuvalu', 'TUV');
INSERT INTO music.country (id, country_name, iso3) VALUES (194, 'Grenada', 'GRD');
INSERT INTO music.country (id, country_name, iso3) VALUES (195, 'San Marino', 'SMR');
INSERT INTO music.country (id, country_name, iso3) VALUES (196, 'West Bank', 'XWB');
INSERT INTO music.country (id, country_name, iso3) VALUES (197, 'Northern Mariana Islands', 'MNP');
INSERT INTO music.country (id, country_name, iso3) VALUES (198, 'Guam', 'GUM');
INSERT INTO music.country (id, country_name, iso3) VALUES (199, 'Palau', 'PLW');
INSERT INTO music.country (id, country_name, iso3) VALUES (200, 'Macau', 'MAC');
INSERT INTO music.country (id, country_name, iso3) VALUES (201, 'Puerto Rico', 'PRI');
INSERT INTO music.country (id, country_name, iso3) VALUES (202, 'Martinique', 'MTQ');
INSERT INTO music.country (id, country_name, iso3) VALUES (203, 'Gibraltar', 'GIB');
INSERT INTO music.country (id, country_name, iso3) VALUES (204, 'Reunion', 'REU');
INSERT INTO music.country (id, country_name, iso3) VALUES (205, 'Guadeloupe', 'GLP');
INSERT INTO music.country (id, country_name, iso3) VALUES (206, 'Curaçao', 'CUW');
INSERT INTO music.country (id, country_name, iso3) VALUES (207, 'French Polynesia', 'PYF');
INSERT INTO music.country (id, country_name, iso3) VALUES (208, 'New Caledonia', 'NCL');
INSERT INTO music.country (id, country_name, iso3) VALUES (209, 'French Guiana', 'GUF');
INSERT INTO music.country (id, country_name, iso3) VALUES (210, 'Aruba', 'ABW');
INSERT INTO music.country (id, country_name, iso3) VALUES (211, 'Jersey', 'JEY');
INSERT INTO music.country (id, country_name, iso3) VALUES (212, 'Mayotte', 'MYT');
INSERT INTO music.country (id, country_name, iso3) VALUES (213, 'Greenland', 'GRL');
INSERT INTO music.country (id, country_name, iso3) VALUES (214, 'Faroe Islands', 'FRO');
INSERT INTO music.country (id, country_name, iso3) VALUES (215, 'Wallis And Futuna', 'WLF');
INSERT INTO music.country (id, country_name, iso3) VALUES (216, 'Saint Helena, Ascension, And Tristan Da Cunha', 'SHN');
INSERT INTO music.country (id, country_name, iso3) VALUES (217, 'Bermuda', 'BMU');
INSERT INTO music.country (id, country_name, iso3) VALUES (218, 'Cayman Islands', 'CYM');
INSERT INTO music.country (id, country_name, iso3) VALUES (219, 'Isle Of Man', 'IMN');
INSERT INTO music.country (id, country_name, iso3) VALUES (220, 'Turks And Caicos Islands', 'TCA');
INSERT INTO music.country (id, country_name, iso3) VALUES (221, 'Cook Islands', 'COK');
INSERT INTO music.country (id, country_name, iso3) VALUES (222, 'Vatican City', 'VAT');
INSERT INTO music.country (id, country_name, iso3) VALUES (223, 'Falkland Islands (Islas Malvinas)', 'FLK');
INSERT INTO music.country (id, country_name, iso3) VALUES (224, 'South Georgia And South Sandwich Islands', 'SGS');